- hosts: install_imageMe
  become: yes
  tasks:
  - name: install the latest version of git
    yum:
      name: git
      state: latest
  - name: install the latest version of python
    yum:
      name: python
      state: latest
  - name: cloning git repository
    git:
      repo: https://github.com/jkanclerz/install-image-me.git
      dest: ~/git
   
  - name: setting variable1
    shell: echo "export SEARCH_ENGINE_ID=006879359584856769921:rplfy3clmho" >> .bashrc
  - name: setting variable2
    shell: echo "export GOOGLE_CLOUD_API_KEY=AIzaSyDLLC1pqOxkWA8jUjM-Cfwbl_13Sh_2t98" >> .bashrc
  
  - name: creating file if it doesn't exist 
    file:
      path: /bin/image_me.sh
      state: touch
      mode: "u+rwx,g+rwx,o+rwx"
  - lineinfile:
      path: /bin/image_me.sh
      line: '#!/bin/bash'
  - lineinfile:
      path: /bin/image_me.sh
      line: 'python /home/ec2-user/google-search-python/image_me.py "$1"'
    
